# Introduction {#intro}

When researching with an organism not present in GeneMANIA[@genemania] it can be beneficial to pool together all the data that you have for your organism and create your own instance.  There are two ways you can create your own instance of GeneMANIA:

  1. Local version of GeneMANIA in cytoscape - only available to you on the device that it is created on.  It is quick to set up and offers all the functionality available in the GeneMANIA cytoscape App.
  1. Local version of GeneMANIA website - if you expose this website to the internet you can share this resource with your colleagues.  Considerably more work to set up but all the code and parts are available in github and docker instances.  
  
  For both of the above instances the bulk of the work required is collecting, translating and creating id conversions and networks, for your desired species, that are used in GeneMANIA.  Given that this is an organism of interest to you likely you have a lot of the information or know where to get it.  

## Overview

  There are three major components to the GeneMANIA system.  (Only the first two are required for both methods of creating your own instance, identifiers and Network, annotation and attribute data):
  
  1. **Identifiers** - mapping from all the different identifiers available for your species of interest.  Ideally the mappping files contain all and any identifiers used for the species.  For example, the human dataset in GeneMANIA has hgnc symbol, entrez gene ids, refseq ids, ensembl ids and uniprot ids.
  1. **Network, annotation and attribure data** - tables of interactions and associations between your entities (enumerated with one of the above identifiers).  Each interaction is associated with a score.  If the data in question doesn't have a score then it has the score of 1 (ie. it is present in the dataset) 
  1. **Indexed data** - Once all the previous data is collected and cleaned the last step involves indexing the data using [lucene](https://lucene.apache.org/). 
  
  For the purpose of this tutorial we will be creating an instance of GeneMANIA using [Tetrahymena](http://ciliate.org/index.php/home/welcome).